// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: appsync/v1/appsync.proto

package appsyncv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MethodOptions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MethodOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MethodOptions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MethodOptionsMultiError, or
// nil if none found.
func (m *MethodOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *MethodOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return MethodOptionsMultiError(errors)
	}

	return nil
}

// MethodOptionsMultiError is an error wrapping multiple validation errors
// returned by MethodOptions.ValidateAll() if the designated constraints
// aren't met.
type MethodOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MethodOptionsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MethodOptionsMultiError) AllErrors() []error { return m }

// MethodOptionsValidationError is the validation error returned by
// MethodOptions.Validate if the designated constraints aren't met.
type MethodOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MethodOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MethodOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MethodOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MethodOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MethodOptionsValidationError) ErrorName() string { return "MethodOptionsValidationError" }

// Error satisfies the builtin error interface
func (e MethodOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMethodOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MethodOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MethodOptionsValidationError{}

// Validate checks the field values on FieldOptions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FieldOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FieldOptions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FieldOptionsMultiError, or
// nil if none found.
func (m *FieldOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *FieldOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ignore

	if len(errors) > 0 {
		return FieldOptionsMultiError(errors)
	}

	return nil
}

// FieldOptionsMultiError is an error wrapping multiple validation errors
// returned by FieldOptions.ValidateAll() if the designated constraints aren't met.
type FieldOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FieldOptionsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FieldOptionsMultiError) AllErrors() []error { return m }

// FieldOptionsValidationError is the validation error returned by
// FieldOptions.Validate if the designated constraints aren't met.
type FieldOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FieldOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FieldOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FieldOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FieldOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FieldOptionsValidationError) ErrorName() string { return "FieldOptionsValidationError" }

// Error satisfies the builtin error interface
func (e FieldOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFieldOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FieldOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FieldOptionsValidationError{}
